apiVersion: v1
kind: Service
metadata:
  name: homarr-svc
  namespace: lab
spec:
  selector:
    app: homarr
  ports:
    - protocol: TCP
      port: 7575
      targetPort: 7575
  type: LoadBalancer
  