---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-apikey-secret
  namespace: kube-system
type: Opaque
stringData:
  email: Cloudflare_email
  apiKey: Cloudflare_API_Token
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
  namespace: kube-system
data:
  traefik-config.yaml: |
    http:
      middlewares:
        headers-default:
          headers:
            sslRedirect: true
            browserXssFilter: true
            contentTypeNosniff: true
            forceSTSHeader: true
            stsIncludeSubdomains: true
            stsPreload: true
            stsSeconds: 15552000
            customFrameOptionsValue: SAMEORIGIN
            customRequestHeaders:
              X-Forwarded-Proto: https  


 