apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-storage
  namespace: lab
  labels:
    app: pihole
spec:
  storageClassName: longhorn-ssd
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi