apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-storage-dns
  namespace: lab
  labels:
    app: pihole
spec:
  storageClassName: longhorn-ssd
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-storage-etc
  namespace: lab
  labels:
    app: pihole
spec:
  storageClassName: longhorn-ssd
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi