apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-storage
  namespace: lab
  labels:
    app: pihole
spec:
  storageClassName: longhorn-ssd
  accessModes:
  - ReadWriteMany #for ReadWriteMany, ensure you have nfs utility installed on the hosts (apt install nfs-common)
  resources:
    requests:
      storage: 5Gi