version: "3"
services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8083:8080
    #command: --interval 86400 --debug list of containers to monitor
    environment:
      WATCHTOWER_DISABLE_CONTAINERS: "it-tools cloudflare-ddns nextcloud-aio-watchtower nextcloud-aio-mastercontainer nextcloud-aio-collabora nextcloud-aio-talk nextcloud-aio-database nextcloud-aio-redis nextcloud-aio-fulltextsearch nextcloud-aio-talk-recording nextcloud-aio-imaginary nextcloud-aio-nextcloud nextcloud-aio-notify-push"
      WATCHTOWER_SCHEDULE: "0 1 * * *"
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_NOTIFICATIONS: email
      WATCHTOWER_NOTIFICATION_EMAIL_FROM: "email@yourdomain.com"
      WATCHTOWER_NOTIFICATION_EMAIL_TO: "emailto@yourdomain.com"
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER: "smtppro.zoho.com"
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER: "email@yourdomain.com"
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD: "loginpass"
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT: "465"
      WATCHTOWER_NOTIFICATION_EMAIL_DELAY: 2
      WATCHTOWER_NOTIFICATIONS_HOSTNAME: "DockerHA"
      TZ: "America/Chicago" 
      WATCHTOWER_NO_STARTUP_MESSAGE: true
      WATCHTOWER_HTTP_API_TOKEN: "anytokenstringthatyouwant"
      WATCHTOWER_HTTP_API_UPDATE: true
      WATCHTOWER_HTTP_API_PERIODIC_POLLS: true
      WATCHTOWER_TIMEOUT: 30s
      