apiVersion: v1
kind: Service
metadata:
  name: kuma-svc
  namespace: lab
spec:
  selector:
    app: uptime-kuma
  ports:
    - protocol: TCP
      name: http
      port: 3001
      targetPort: 3001
  type: NodePort
  