apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homer-data
  namespace: lab
spec:
  storageClassName: longhorn-hdd
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi