apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homer-data
  namespace: lab
spec:
  storageClassName: longhorn-ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi