apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: heimdall-data
  namespace: lab
spec:
  storageClassName: longhorn-hdd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi