apiVersion: v1
kind: Service
metadata:
  name: heimdall-svc
  namespace: lab
spec:
  selector:
    app: heimdall
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
    - protocol: TCP
      name: https
      port: 443
      targetPort: 443
  type: LoadBalancer
  