apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dashy-pv
  namespace: lab
  labels:
    app: dashy
spec:
  storageClassName: longhorn-hdd
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi 